### ISSUE TITLE
Rare occasional panic in tests

### ISSUE THREAD

**Issue by kuredoro** [kuredoro/cptest#1]
The runtime and internal error test for TestingBatch can occasionally panic or fail.

Error reported on occasional fail:
```
TestingBatch_test.go:163: test was called 4 times, want 5
```

Backtrace for panic:
```
fatal error: concurrent map read and map write

goroutine 45 [running]:
runtime.throw(0x5a7e3a, 0x21)
	/usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc000111cf8 sp=0xc000111cc8 pc=0x436d52
runtime.mapaccess1_fast64(0x578260, 0xc000108e70, 0x2, 0xc000178af8)
	/usr/lib/go/src/runtime/map_fast64.go:21 +0x198 fp=0xc000111d20 sp=0xc000111cf8 pc=0x4120b8
github.com/kureduro/cptest.(*TestingBatch).Run(0xc00014e280)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:165 +0x445 fp=0xc000111e48 sp=0xc000111d20 pc=0x54f825
github.com/kureduro/cptest_test.TestTestingBatch.func3(0xc000170c00)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch_test.go:152 +0x2bb fp=0xc000111f80 sp=0xc000111e48 pc=0x55629b
testing.tRunner(0xc000170c00, 0x5ac9a8)
	/usr/lib/go/src/testing/testing.go:1123 +0xef fp=0xc000111fd0 sp=0xc000111f80 pc=0x50228f
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000111fd8 sp=0xc000111fd0 pc=0x46db21
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1168 +0x2b3

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000170480, 0x5a3438, 0x10, 0x5ac9c0, 0x48c901)
	/usr/lib/go/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc00011e180)
	/usr/lib/go/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc00011e180, 0xc00008dde0)
	/usr/lib/go/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00012c120, 0x6b1ec0, 0x6, 0x6, 0xbfde77c668101ca4, 0x8bb2cc8dae, 0x6b5b00, 0x40d430)
	/usr/lib/go/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc00014e000, 0x0)
	/usr/lib/go/src/testing/testing.go:1345 +0x1eb
main.main()
	_testmain.go:55 +0x138

goroutine 38 [chan receive]:
testing.(*T).Run(0xc000170c00, 0x5a7ab0, 0x20, 0x5ac9a8, 0x2e50d58e501)
	/usr/lib/go/src/testing/testing.go:1169 +0x2da
github.com/kureduro/cptest_test.TestTestingBatch(0xc000170480)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch_test.go:100 +0xae
testing.tRunner(0xc000170480, 0x5ac9c0)
	/usr/lib/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1168 +0x2b3

goroutine 46 [chan send]:
github.com/kureduro/cptest.(*TestingBatch).launchTest.func1.1(0xc00014e280, 0x1)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:109 +0x1f9
github.com/kureduro/cptest.(*TestingBatch).launchTest.func1(0xc00014e280, 0x1, 0x5a0c3d, 0x1)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:120 +0x2bf
created by github.com/kureduro/cptest.(*TestingBatch).launchTest
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:99 +0x5d

goroutine 48 [chan send]:
github.com/kureduro/cptest.(*TestingBatch).launchTest.func1.1(0xc00014e280, 0x3)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:109 +0x1f9
github.com/kureduro/cptest.(*TestingBatch).launchTest.func1(0xc00014e280, 0x3, 0x5a0c3f, 0x1)
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:120 +0x2bf
created by github.com/kureduro/cptest.(*TestingBatch).launchTest
	/home/nekonyaaa/code/skyarrow/cptest/TestingBatch.go:99 +0x5d
```

Possibly this is issue with the defer statement in `launchTest` function. However, further investigation is needed.

**Comment by kuredoro** [comment]
Another instance:
```
fatal error: concurrent map read and map write

goroutine 5 [running]:
runtime.throw(0x5a9082, 0x21)
	/opt/hostedtoolcache/go/1.15.3/x64/src/runtime/panic.go:1116 +0x72 fp=0xc000090cf0 sp=0xc000090cc0 pc=0x436d52
runtime.mapaccess1_fast64(0x579320, 0xc0000100f0, 0x2, 0xc000060200)
	/opt/hostedtoolcache/go/1.15.3/x64/src/runtime/map_fast64.go:21 +0x198 fp=0xc000090d18 sp=0xc000090cf0 pc=0x4120b8
github.com/kuredoro/cptest.(*TestingBatch).Run(0xc00006e080)
	/home/runner/work/cptest/cptest/TestingBatch.go:173 +0x346 fp=0xc000090e10 sp=0xc000090d18 pc=0x54f7e6
github.com/kuredoro/cptest_test.TestAcceptanceSimple(0xc000001080)
	/home/runner/work/cptest/cptest/acceptance_test.go:34 +0x21f fp=0xc000090f80 sp=0xc000090e10 pc=0x553a1f
testing.tRunner(0xc000001080, 0x5adcf0)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1123 +0xef fp=0xc000090fd0 sp=0xc000090f80 pc=0x50228f
runtime.goexit()
	/opt/hostedtoolcache/go/1.15.3/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000090fd8 sp=0xc000090fd0 pc=0x46db21
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1168 +0x2b3

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000001080, 0x5a5779, 0x14, 0x5adcf0, 0x48c901)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc0000a0180)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc0000a0180, 0xc0000cbda8)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1123 +0xef
testing.runTests(0xc0000ae120, 0x6b6840, 0x7, 0x7, 0xbfe12108ede00ef5, 0x8bb2cd2efd, 0x6ba3e0, 0x40d430)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc0000e2000, 0x0)
	/opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1345 +0x1eb
main.main()
	_testmain.go:113 +0x1c5

goroutine 59 [sleep]:
time.Sleep(0x1312d00)
	/opt/hostedtoolcache/go/1.15.3/x64/src/runtime/time.go:188 +0xbf
github.com/kuredoro/cptest_test.TestTestingBatch.func4.1(0x5d68c0, 0xc0000af820, 0x5d66c0, 0xc000089230, 0x0, 0x0)
	/home/runner/work/cptest/cptest/TestingBatch_test.go:181 +0xa5
github.com/kuredoro/cptest.ProcesserFunc.Run(0x5ade08, 0x5d68c0, 0xc0000af820, 0x5d66c0, 0xc000089230, 0x1, 0xc0000af820)
	/home/runner/work/cptest/cptest/processer.go:34 +0x58
github.com/kuredoro/cptest.(*SpyProcesser).Run(0xc0000af800, 0x5d68c0, 0xc0000af820, 0x5d66c0, 0xc000089230, 0x0, 0x0)
	/home/runner/work/cptest/cptest/processer.go:25 +0x69
github.com/kuredoro/cptest.(*TestingBatch).launchTest.func1(0xc0000e2580, 0x4, 0x5a1e4c, 0x2)
	/home/runner/work/cptest/cptest/TestingBatch.go:120 +0x12d
created by github.com/kuredoro/cptest.(*TestingBatch).launchTest
	/home/runner/work/cptest/cptest/TestingBatch.go:106 +0x67

goroutine 58 [sleep]:
time.Sleep(0xe4e1c0)
	/opt/hostedtoolcache/go/1.15.3/x64/src/runtime/time.go:188 +0xbf
github.com/kuredoro/cptest_test.TestTestingBatch.func4.1(0x5d68c0, 0xc0000af8a0, 0x5d66c0, 0xc0000892c0, 0x0, 0x0)
	/home/runner/work/cptest/cptest/TestingBatch_test.go:181 +0xa5
github.com/kuredoro/cptest.ProcesserFunc.Run(0x5ade08, 0x5d68c0, 0xc0000af8a0, 0x5d66c0, 0xc0000892c0, 0x1, 0xc0000af8a0)
	/home/runner/work/cptest/cptest/processer.go:34 +0x58
github.com/kuredoro/cptest.(*SpyProcesser).Run(0xc0000af800, 0x5d68c0, 0xc0000af8a0, 0x5d66c0, 0xc0000892c0, 0x0, 0x0)
	/home/runner/work/cptest/cptest/processer.go:25 +0x69
github.com/kuredoro/cptest.(*TestingBatch).launchTest.func1(0xc0000e2580, 0x3, 0x5a1e4a, 0x2)
	/home/runner/work/cptest/cptest/TestingBatch.go:120 +0x12d
created by github.com/kuredoro/cptest.(*TestingBatch).launchTest
	/home/runner/work/cptest/cptest/TestingBatch.go:106 +0x67

goroutine 7 [chan send]:
github.com/kuredoro/cptest.(*TestingBatch).launchTest.func1.1(0xc00006e080, 0x1)
	/home/runner/work/cptest/cptest/TestingBatch.go:116 +0x219
github.com/kuredoro/cptest.(*TestingBatch).launchTest.func1(0xc00006e080, 0x1, 0xc00001c108, 0x4)
	/home/runner/work/cptest/cptest/TestingBatch.go:127 +0x2b7
created by github.com/kuredoro/cptest.(*TestingBatch).launchTest
	/home/runner/work/cptest/cptest/TestingBatch.go:106 +0x67
exit status 2
```
