### ISSUE TITLE
Configuration is not validated

### ISSUE THREAD

**Issue by kuredoro** [kuredoro/cptest#25]
Test suite configuration can be defined as the first test case in the inputs file. The problem is that the values are not checked in any way. For instance,
```
tl = -1.5
prec = -1
===
1.234
---
1.234
```
Will result in panic:
```
fatal error: concurrent map read and map write
```

Additionally, command line arguments should be checker also. Specifically, `-j` flag that can be invoked with negative numbers:
```
$ cptest -j -5 a.out
panic: makechan: size out of range

goroutine 1 [running]:
github.com/shettyh/threadpool.NewThreadPool(0xfffffffffffffffb, 0xfffffffffffffffb, 0x400)
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/threadpool.go:22 +0x65
github.com/kuredoro/cptest.NewThreadPool(...)
	/cptest/thread_pool.go:39
main.main()
	cptest/cmd/cptest/main.go:127 +0x2f0
```

**Comment by kuredoro** [comment]
`cptest -j 0` also *silently* sets jobs to default.
