### ISSUE TITLE
Printer callback promotes accessing `TestingBatch` without synchronization.

### ISSUE THREAD

**Issue by kuredoro** [kuredoro/cptest#29]
Reproducible, but not always:
```
$ cptest .
< aronud 100 tests >

Error:
executable: fork/exec /home/nekonyaaa/code/skyarrow/cptest/eg/04_1000_tests: permission denied

fatal error: concurrent map read and map write

goroutine 68 [running]:
runtime.throw({0x526637, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00019fea0 sp=0xc00019fe70 pc=0x432831
runtime.mapaccess1_fast64(0x54b280, 0xc0000b2060, 0x54)
	/usr/local/go/src/runtime/map_fast64.go:21 +0x172 fp=0xc00019fec0 sp=0xc00019fea0 pc=0x411332
main.printVerboseResult(0xc0004b4000)
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/printer.go:64 +0x2fa fp=0xc00019ff88 sp=0xc00019fec0 pc=0x4f1cda
main.verboseResultPrinterWorker()
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/printer.go:34 +0x3e fp=0xc00019ffb8 sp=0xc00019ff88 pc=0x4f199e
main.main.func1()
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/main.go:163 +0x25 fp=0xc00019ffe0 sp=0xc00019ffb8 pc=0x4f17e5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00019ffe8 sp=0xc00019ffe0 pc=0x460ba1
created by main.main
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/main.go:162 +0x665

goroutine 1 [select]:
github.com/kuredoro/cptest.(*TestingBatch).Run(0xc00018c0c0)
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:208 +0x314
main.main()
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/main.go:167 +0x672

goroutine 6 [runnable]:
os.newFile(0xa, {0x51fa7d, 0x2}, 0x2)
	/usr/local/go/src/os/file_unix.go:123 +0x1a9
os.Pipe()
	/usr/local/go/src/os/pipe_linux.go:32 +0x1a5
os/exec.(*Cmd).StdoutPipe(0xc00049e000)
	/usr/local/go/src/os/exec/exec.go:626 +0x3e
main.(*Executable).Run(0x504820, {0x54d298, 0xc000518040}, {0x54b2a0, 0xc000204000})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:21 +0xe5
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x61, {0xc0001347b0, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc000264480)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc000057fb0, 0xc000057f90, 0x0}, {0x504520, 0xc0004a2000})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 7 [runnable]:
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:22 +0xa8
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 8 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0003a7400)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0003f7b00)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc000395550, 0x1, 0x1}, 0x619426f900000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc0003f78c0}, {0xc000395550, 0x1, 0x1}, 0xc0004bbbf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc000395550, 0x1, 0x1}, 0x7fcb68255448)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc0003fe420)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc0003b73c0}, {0x54b2a0, 0xc00039ba20})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5a, {0xc000134740, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036d8c0)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc0004bbfb0, 0xc0004bbf90, 0x0}, {0x504520, 0xc0003167b0})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 9 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0004aca00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000788240)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc00049aa20, 0x1, 0x1}, 0xeafdb8a800000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000788000}, {0xc00049aa20, 0x1, 0x1}, 0xc000058bf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc00049aa20, 0x1, 0x1}, 0x7fcb682d6878)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc00049f340)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000498ac0}, {0x54b2a0, 0xc00049cc80})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x59, {0xc000134730, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc000264360)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc000058fb0, 0xc000058f90, 0x0}, {0x504520, 0xc0004a2540})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 10 [runnable]:
sync.runtime_Semrelease(0x0, 0x0, 0x2336)
	/usr/local/go/src/runtime/sema.go:66 +0x19
sync.(*Mutex).unlockSlow(0x0, 0x0)
	/usr/local/go/src/sync/mutex.go:224 +0x65
sync.(*Mutex).Unlock(...)
	/usr/local/go/src/sync/mutex.go:190
sync.(*RWMutex).Unlock(0x637ae0)
	/usr/local/go/src/sync/rwmutex.go:149 +0x9b
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc00049a850, 0x1, 0x1}, 0x199303200000300)
	/usr/local/go/src/syscall/exec_unix.go:217 +0x3c6
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc0004fdb00}, {0xc00049a850, 0x1, 0x1}, 0xc000514bf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc00049a850, 0x1, 0x1}, 0x7fcb682d6878)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc00049f1e0)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000498a00}, {0x54b2a0, 0xc00049ca40})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x56, {0xc000134700, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036d7a0)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc000514fb0, 0xc000514f90, 0x0}, {0x504520, 0xc000316780})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 11 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc00022aa00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000239d40)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc000202b90, 0x1, 0x1}, 0x84d3fd9e00000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000239b00}, {0xc000202b90, 0x1, 0x1}, 0xc000515bf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc000202b90, 0x1, 0x1}, 0x7fcb682f1be0)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc0002111e0)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000200a00}, {0x54b2a0, 0xc000204e60})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x58, {0xc000134720, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc0002645a0)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc000515fb0, 0xc000515f90, 0x0}, {0x504520, 0xc0004a2510})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 12 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc00058e100)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0x637ae0)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc0005080b0, 0x1, 0x1}, 0xd35dc13800000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc00050ab40}, {0xc0005080b0, 0x1, 0x1}, 0xc00043fbf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc0005080b0, 0x1, 0x1}, 0x7fcb681c5c40)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc0005802c0)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000506180}, {0x54b2a0, 0xc00050c0e0})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5f, {0xc000134790, 0x3})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036daa0)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc00043ffb0, 0xc00043ff90, 0x0}, {0x504520, 0xc00028a000})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 13 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0004acb00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000788b40)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc00049aac0, 0x1, 0x1}, 0x1a17021300010300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000788900}, {0xc00049aac0, 0x1, 0x1}, 0xc0000c5bf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc00049aac0, 0x1, 0x1}, 0x7fcb682d6878)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc00049f600)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000498c40}, {0x54b2a0, 0xc00049cd40})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5c, {0xc000134760, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036db00)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc0000c5fb0, 0xc0000c5f90, 0x0}, {0x504520, 0xc000316810})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 14 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0004acb00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000788fc0)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc00049ab10, 0x1, 0x1}, 0xf101348200000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000788d80}, {0xc00049ab10, 0x1, 0x1}, 0xc000510bf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc00049ab10, 0x1, 0x1}, 0x7fcb682d6878)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc00049f760)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000498d00}, {0x54b2a0, 0xc00049cda0})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5d, {0xc000134770, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc000215f20)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc000510fb0, 0xc000510f90, 0x0}, {0x504520, 0xc0003989f0})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 15 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0003a7500)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000706000)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc000395620, 0x1, 0x1}, 0x9ae60efd00000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc0003f7d40}, {0xc000395620, 0x1, 0x1}, 0xc0004bfbf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc000395620, 0x1, 0x1}, 0x7fcb68255448)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc0003fe580)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc0003b7480}, {0x54b2a0, 0xc00039bb20})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5e, {0xc000134780, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036dc20)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc0004bffb0, 0xc0004bff90, 0x0}, {0x504520, 0xc000316840})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 16 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc00022aa00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0002398c0)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc000202b40, 0x1, 0x1}, 0xa50aaa1f00000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000239680}, {0xc000202b40, 0x1, 0x1}, 0xc00043bbf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc000202b40, 0x1, 0x1}, 0x7fcb682f1be0)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc000211080)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000200940}, {0x54b2a0, 0xc000204e00})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x57, {0xc000134710, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036d620)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc00043bfb0, 0xc00043bf90, 0x0}, {0x504520, 0xc0004a24e0})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 66 [semacquire]:
sync.runtime_SemacquireMutex(0xc000022000, 0x44, 0xc0004aca00)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x637ae0)
	/usr/local/go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0007886c0)
	/usr/local/go/src/sync/rwmutex.go:111 +0x36
syscall.forkExec({0xc00001a0c0, 0xc000022000}, {0xc00049aa70, 0x1, 0x1}, 0xa6f0a1800000300)
	/usr/local/go/src/syscall/exec_unix.go:204 +0x312
syscall.StartProcess(...)
	/usr/local/go/src/syscall/exec_unix.go:264
os.startProcess({0xc00001a0c0, 0xc000788480}, {0xc00049aa70, 0x1, 0x1}, 0xc00021bbf0)
	/usr/local/go/src/os/exec_posix.go:55 +0x332
os.StartProcess({0xc00001a0c0, 0x35}, {0xc00049aa70, 0x1, 0x1}, 0x7fcb682d6878)
	/usr/local/go/src/os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc00049f4a0)
	/usr/local/go/src/os/exec/exec.go:422 +0x60a
main.(*Executable).Run(0x504820, {0x54d298, 0xc000498b80}, {0x54b2a0, 0xc00049cce0})
	/home/nekonyaaa/code/skyarrow/cptest/cmd/cptest/executable.go:31 +0x2ae
github.com/kuredoro/cptest.(*TestingBatch).launchTest(0xc00018c0c0, 0x5b, {0xc000134750, 0x4})
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:155 +0x2b9
github.com/kuredoro/cptest.(*TestingBatch).Run.func3()
	/home/nekonyaaa/code/skyarrow/cptest/testing_batch.go:230 +0x3e
github.com/kuredoro/cptest.RunnableFunc.Run(0xc00036d9e0)
	/home/nekonyaaa/code/skyarrow/cptest/thread_pool.go:22 +0x1a
github.com/shettyh/threadpool.Worker.executeJob({0xc00021bfb0, 0xc00021bf90, 0x0}, {0x504520, 0xc0003167e0})
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:40 +0xc2
github.com/shettyh/threadpool.Worker.Start.func1()
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:26 +0x3f
created by github.com/shettyh/threadpool.Worker.Start
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/worker.go:17 +0xaf

goroutine 67 [select]:
github.com/shettyh/threadpool.(*ThreadPool).dispatch(0xc00009a270)
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/threadpool.go:78 +0xeb
created by github.com/shettyh/threadpool.(*ThreadPool).createPool
	/home/nekonyaaa/go/pkg/mod/github.com/shettyh/threadpool@v0.0.0-20200323115144-b99fd8aaa945/threadpool.go:71 +0xaf
```

**Comment by kuredoro** [comment]
Reproducible 100% when `tl` is rather small.
